### ISSUE TITLE
Exclude "lore" text in card text search

### ISSUE THREAD

**Issue by thenamelessthing** [rezwits/cardnum#10]
Hi, it will be better if we can search un card text excluding "lore" text. Maybe to add checkbox if we want to search in both but by default only in the game text?

Thanks you for your work!

**Comment by rezwits** [comment]
Yes true indeed.  The only issue is, the regular text and lore text are all one field.  Someone would have to sift thru the data, and separate those, into two field.  Or have a database with all the corrections of the "game text" we've done, and then the "lore text" seperated.  Which a...  Would be nice if this could be as simple as just adding another check box.  :D
