### ISSUE TITLE
REQUEST: replace chat with discord server

### ISSUE THREAD

**Issue by thenamelessthing** [rezwits/cardnum#11]
Hi, I really like cardnum. But to increase the playability and the fun. I think , replace the actual chat with discord server will be much better. Because we can have text chat and "audio" chat. This will transform game like people was there in person.. Also, it people can be reachable on pc and smartphone. So it will be more easy the schedule games. I don't know if this can be done easily, but I think at least you must consider the option.

I setup an discord server at this address:  https://discord.gg/JDQ5j2

**Comment by rezwits** [comment]
How's this one working out? haha. So glad you built the discord server, hope that's not too consuming...
