### ISSUE TITLE
Suggestion: replace or add the possibility to use the discord chat 

### ISSUE THREAD

**Issue by thenamelessthing** [rezwits/cardnum#14]
Hi, I really like cardnum. But I think replacing or give the choice to the users to use discord chat can be a great upgrade. I can help by providing admin account to the discord server:

Here is the code for the discord Widget:

<iframe src="https://discordapp.com/widget?id=688058353519427660&theme=dark" width="350" height="500" allowtransparency="true" frameborder="0"></iframe>

Discord advantage are:

1. Text/voice/video chat
2. Available on almost every platform
3. More modern interface

The discord server address is: https://discord.gg/65wegEj  

But I think you already know that! ;-)

**Comment by rezwits** [comment]
– Nameless

Do you know if there are any easily defined hooks that I can use to just simply replace it?  (In like a day or two?). I haven’t seen much conversation, on just simply adding the widget.  The thing about the site, is it “looks” like a plain old HTML server but it’s not even close.  It’s a self-contained App, that’s just running it’s own private Clojure code inside a java shell.

I mean if I can get a few days to “investigate” maybe I can come up with something, but unfortunately I am dealing with some family things that I have told some people about but would like kept private.

But I will get some time to “check things”

Thx

- Tom

**Comment by rezwits** [comment]
How's this one working out? haha. So glad you built the discord server, hope that's not too consuming...
I hope the permanent link at the top is still working out...
