### ISSUE TITLE
Suggestion: Make card rarity visible when a card is selected

### ISSUE THREAD

**Issue by scottrick** [rezwits/cardnum#15]
For a newer player like myself, there's no easy way to tell what the rarity of a card is (that I know of).  It would be awesome if that once I've selected a card (when browsing via http://cardnum.net/cards) that in the Card Text box it also listed the rarity.  For example:

The Wizards (C1): A Chance Meeting
or
The Wizards (R1): Arwen

**Comment by rezwits** [comment]
Great point, I will definitely get to adding the rairty in the card text box! 100%. That's an easy one...

**Comment by rezwits** [comment]
Ok, there is a small hack for now that shows the R, U, C, CB1 etc for the cards, till I can get to a full update, you need to force reload to see the change and DC don't have rarity at this time.

**Comment by scottrick** [comment]
Thanks, that's awesome!
