### ISSUE TITLE
Leftside panel not scrollable.

### ISSUE THREAD

**Issue by scottrick** [rezwits/cardnum#16]
The leftside dark-blue semi-transparent panel is not scrollable.  With some cards, (Await the Onset for example) the "Card text" at the bottom is cut off, and you cannot scroll down to see the rest of the text.  Here is a screenshot showing an example of the left-hand side of my screen.  I'm unable to scroll the panel down and see the rest of the text:

<img width="625" alt="Screen Shot 2020-08-03 at 8 34 14 AM" src="https://user-images.githubusercontent.com/643675/89188426-40460d00-d564-11ea-9a5b-60ce55795f36.png">

**Comment by rezwits** [comment]
For this I went with the simple toggle of "Show Terms."  If you click that then you will see the text below from a clicked card.
