### ISSUE TITLE
deck builder not showing ICE errata even though selected in settings

### ISSUE THREAD

**Issue by davidk64fnq** [rezwits/cardnum#17]
Vastor and I troubleshooted it a week or so back and initially he couldn't reproduce it but then he could. Not urgent as I think they show okay in play and I look at the card pictures in The Wizards Player Guide which include errata.

**Comment by rezwits** [comment]
I hope you got this all figured out, I thought maybe, when I told Vastor, you probably just didn't click on ICE errata, and then refresh...
