### ISSUE TITLE
Deck builder wizard/fallen wizard name collision

### ISSUE THREAD

**Issue by nuke-ellington** [rezwits/cardnum#8]
It appears to be impossible to add the original wizards to a deck, since they have the exact same card names as their fallen counterparts.
Not sure if that is only the deck builder showing the wrong image while the correct card is getting added to the deck.

**Comment by rezwits** [comment]
This project is a minor migration from the old GCCG MECCG, i.e. it uses codes from the old deck format used by GCCG+MECCG.

When adding cards, there are alignments and/or sets, for example:

Gandalf [H] (TW)
Gandalf [F] (WH)

Avatars in all cases should their appropriate code.
One thing to note when adjusting an alignment and/or set, is do a quick +(plus) then a - (minus), to register your change.
