### ISSUE TITLE
New choice in Deck Builder Avatar

### ISSUE THREAD

**Issue by KakitaBen** [rezwits/cardnum#9]
Hi there,

Can you please allow the choice "NONE" in avatar when building a deck, some hamburger scenario do not allow playing a wizard.

+++

Ben

**Comment by rezwits** [comment]
– Ben

What we resolved is, everyone picks FW Alatar/Gandalf/AnyFW, and don’t put any Avatars in your deck.

This way both players will get all sites. i.e. Hero and Minion.

And all players can load any cards they want.  This will not prohibit anything.

All should be good?

Let me know, if this doesn’t make sense.

Or what you are lacking?

– Tom

**Comment by rezwits** [comment]
– Ben

What we resolved is, everyone picks FW Alatar/Gandalf/AnyFW, and don’t put any Avatars in your deck.

This way both players will get all sites. i.e. Hero and Minion.

And all players can load any cards they want.  This will not prohibit anything.

All should be good?

Let me know, if this doesn’t make sense.

Or what you are lacking?

– Tom

And I could put the Avatar less avatar pick, in as None, with an icon? But they are best considered in the FW section right?
Or Elf-lord? Where they get 3 Hero Resource? Or 2 Hero Resource?

Let me know!

**Comment by rezwits** [comment]
Did you get this update?

**Comment by KakitaBen** [comment]
Yep good news thx 😊

De : Thomas Aldershof II <notifications@github.com>
Envoyé : mardi 24 mars 2020 04:51
À : rezwits/cardnum <cardnum@noreply.github.com>
Cc : KakitaBen <bayushiyoshiko@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [rezwits/cardnum] New choice in Deck Builder Avatar (#9)


Did you get this update?
